apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: ysfaksn/go-apigateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: PG_CONN
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: pg-connection
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: app-key
        resources:
          requests:
            cpu: "10m"
            memory: "50Mi"
          limits:
            cpu: "20m"
            memory: "100Mi"
