apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  pg-connection: cG9zdGdyZXM6Ly9kYXRhYmFzZXBvc3RncmVzcWxfdXNlcjpkYXRhYmFzZXBvc3RncmVzcWxfcGFzc3dvcmRAbG9jYWxob3N0OjU0MzIvZGF0YWJhc2Vwb3N0Z3Jlc3FsP3NzbG1vZGU9ZGlzYWJsZQ==
  app-key: YWtATG9tbitAIXBjelJlYVJwcDN6QCE=