apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  pg-connection: cG9zdGdyZXM6Ly9kYXRhYmFzZXBvc3RncmVzcWxfdXNlcjpkYXRhYmFzZXBvc3RncmVzcWxfcGFzc3dvcmRAaG9zdC5kb2NrZXIuaW50ZXJuYWw6NTQzMi9kYXRhYmFzZXBvc3RncmVzcWw/c3NsbW9kZT1kaXNhYmxl
  app-key: YWtATG9tbitAIXBjelJlYVJwcDN6QCE=